#!/usr/bin/env python3
"""
VTT to Subtitles script
Converts edge-tts generated WebVTT subtitle files to Remotion-compatible
TypeScript subtitles data (SubtitleItem interface, subtitles array, and TOTAL_FRAMES).
"""

import argparse
import re
import sys
from pathlib import Path
from typing import List, Tuple


# Regex pattern to match VTT timestamps: e.g. "00:00:01.234 --> 00:00:04.567"
TIMESTAMP_PATTERN = re.compile(
    r"(\d{2}):(\d{2}):(\d{2})[.,](\d{3})\s*-->\s*(\d{2}):(\d{2}):(\d{2})[.,](\d{3})"
)


def parse_timestamp_to_seconds(match: re.Match, start_group_offset: int) -> float:
    """Converts a matched timestamp group into seconds."""
    hours = int(match.group(start_group_offset))
    minutes = int(match.group(start_group_offset + 1))
    seconds = int(match.group(start_group_offset + 2))
    milliseconds = int(match.group(start_group_offset + 3))
    return hours * 3600 + minutes * 60 + seconds + milliseconds / 1000.0


def parse_vtt(vtt_path: Path, fps: int) -> Tuple[List[Tuple[float, float, str]], int]:
    """Parses a WebVTT file and returns a list of cues (start_sec, end_sec, text) and total frames."""
    if not vtt_path.exists():
        raise FileNotFoundError(f"VTT file not found: {vtt_path}")

    with open(vtt_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Split cues using double newlines
    blocks = content.strip().split("\n\n")
    cues = []

    for block in blocks:
        lines = [line.strip() for line in block.strip().split("\n") if line.strip()]
        if len(lines) < 2:
            continue

        # Find the line containing the timestamp
        timestamp_line = ""
        text_line = ""
        
        for idx, line in enumerate(lines):
            if "-->" in line:
                timestamp_line = line
                # Subtitle text is the remaining lines concatenated
                text_line = " ".join(lines[idx + 1:])
                break

        if not timestamp_line:
            continue

        match = TIMESTAMP_PATTERN.search(timestamp_line)
        if not match:
            continue

        try:
            start_sec = parse_timestamp_to_seconds(match, 1)
            end_sec = parse_timestamp_to_seconds(match, 5)
            # Escape double quotes for TypeScript compatibility
            text = text_line.replace('"', '\\"')
            cues.append((start_sec, end_sec, text))
        except (ValueError, IndexError) as e:
            print(f"Warning: Failed to parse timestamp line '{timestamp_line}': {e}", file=sys.stderr)
            continue

    if not cues:
        raise ValueError(f"No valid subtitle cues found in {vtt_path}")

    # Add extra padding of 30 frames (1 second) past the last subtitle
    total_frames = int(cues[-1][1] * fps) + fps
    return cues, total_frames


def generate_typescript_code(cues: List[Tuple[float, float, str]], total_frames: int, fps: int) -> str:
    """Generates the TypeScript file content."""
    lines = [
        "// Generated by vtt_to_subtitles.py. Do not edit manually.",
        "",
        "export interface SubtitleItem {",
        "  index: number;",
        "  startFrame: number;",
        "  endFrame: number;",
        "  startSec: number;",
        "  endSec: number;",
        "  text: string;",
        "}",
        "",
        "export const subtitles: SubtitleItem[] = ["
    ]

    for idx, (start_sec, end_sec, text) in enumerate(cues):
        start_frame = int(start_sec * fps)
        end_frame = int(end_sec * fps)
        lines.append(
            f'  {{ index: {idx + 1}, startFrame: {start_frame}, endFrame: {end_frame}, '
            f'startSec: {start_sec:.3f}, endSec: {end_sec:.3f}, text: "{text}" }},'
        )

    lines.append("];")
    lines.append("")
    lines.append(f"export const TOTAL_FRAMES = {total_frames};")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Convert edge-tts WebVTT files to Remotion subtitles.ts."
    )
    parser.add_argument(
        "vtt_file",
        type=str,
        help="Path to the WebVTT file (e.g. narration.vtt)"
    )
    parser.add_argument(
        "--fps",
        type=int,
        default=30,
        help="Frame rate (default: 30)"
    )
    parser.add_argument(
        "-o", "--output",
        type=str,
        default=None,
        help="Output file path (default: print to stdout)"
    )

    args = parser.parse_args()
    vtt_path = Path(args.vtt_file)

    try:
        cues, total_frames = parse_vtt(vtt_path, args.fps)
        ts_code = generate_typescript_code(cues, total_frames, args.fps)

        if args.output:
            output_path = Path(args.output)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(ts_code)
            print(f"Successfully converted subtitle cues to: {output_path}", file=sys.stderr)
        else:
            sys.stdout.write(ts_code)
            sys.stdout.flush()
            
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
